#!/usr/bin/env bash
#SBATCH -J Panaroo
#SBATCH -p long
#SBATCH --mem=50G
#SBATCH --nodes=1 ###Does the job need to be run across nodes?
#SBATCH --ntasks=1 ###Number of tasks running simultaneously
#SBATCH -c 10 ###Number of cpus needed for each task

### Path of this script: sbatch /home/zzeng/git_hub/scripts/pseudomonasAnalysis/Panaroo_LL.sh ###

### Create a temporary working directory on the scratch space ###
BB_WORKDIR=$(mktemp -d /mnt/shared/scratch/zzeng/${USER}_${SLURM_JOBID}.XXXXXX)
export TMPDIR=${BB_WORKDIR}

### Ensure the script stops on any error ###
set -e

source /mnt/apps/users/zzeng/conda/bin/activate /mnt/apps/users/zzeng/conda/envs/panaroo

### Set paths ###
# BAKTA_OUTPUT_DIR="/mnt/shared/scratch/zzeng/bakta/results_PG2d302"  
PANAROO_INPUT_DIR="/mnt/shared/scratch/zzeng/Panaroo/LightDB_PG2d302_PG2dSubclade17/Input"
PANAROO_OUTPUT_DIR="/mnt/shared/scratch/zzeng/Panaroo/LightDB_PG2d302_PG2dSubclade17/Output_98"

### Create directories for Panaroo input and output ###
# mkdir -p $PANAROO_INPUT_DIR
mkdir -p $PANAROO_OUTPUT_DIR

### Collect all .gff3 files from nested Bakta output folders ###
# echo "Collecting .gff3 files from Bakta output..."
# find "$BAKTA_OUTPUT_DIR" -mindepth 2 -type f -name "*.gff3" -exec cp {} "$PANAROO_INPUT_DIR" \;
# 
# ### Check if any files were collected ###
# if [ "$(ls -A $PANAROO_INPUT_DIR)" ]; then
#     echo "Found $(ls -1 $PANAROO_INPUT_DIR | wc -l) GFF files. Proceeding with Panaroo..."
# else
#     echo "No GFF files found! Please check your Bakta annotations."
#     exit 1
# fi

### Run Panaroo ###
echo "Running Panaroo..."
panaroo \
-i "${PANAROO_INPUT_DIR}"/*.gff3 \
-o $PANAROO_OUTPUT_DIR \
--clean-mode strict \
--merge_paralogs \
--aligner mafft \
-c 0.98 \
--len_dif_percent 0.98 \
-a pan \
--core_threshold 0.98 \
-t 10

### -c 0.98 Clustering threshold. Defines the sequence identity for clustering genes into gene families. Genes sharing ≥98% sequence identity are grouped together. ###
### --len_dif_percent 0.98 For clustering genes. This sets the  maximum allowed difference in gene length (as a fraction) between homologous genes during clustering. ###
### --core_threshold 0.98 Core genome definition. A gene is considered core if it is found in ≥98% of genomes ###
### -f 0.5 Amino acid identity threshold for grouping gene families ###

### Check for completion ###
if [ $? -eq 0 ]; then
    echo "Panaroo completed successfully! Results are in $PANAROO_OUTPUT_DIR"
else
    echo "Panaroo encountered an error. Check the log for details."
    exit 1
fi

test -d ${BB_WORKDIR} && /bin/rm -rf ${BB_WORKDIR}